build.config.msm.autogvm
build.config.msm.sun
build.config.msm.sun.allyes
build.config.msm.canoe
build.config.msm.alor.le
build.config.msm.bengal
build.config.msm.lahaina
build.config.msm.monaco
build.config.msm.seraph
build.config.msm.vienna
build.config.msm.vienna.le
build.config.msm.gen3auto
build.config.msm.hamoa
build.config.msm.malabar
build.config.msm.pikachu
build.config.msm.shikra
