LINUXINCLUDE    += -I$(EVA_ROOT)/include \
                   -I$(EVA_ROOT)/include/uapi \
				   -I$(EVA_ROOT)/include/uapi/eva

#srctree is /kernel_platform/common/

ccflags-y += -I$(EVA_ROOT)/msm/eva/ \
    -I$(srctree)/drivers/media/platform/msm/synx/

# add flag to compile mmrm actual implementatio instead of stub version.
# to follow up with mmrm team if techpack users need to define this for long term?
KBUILD_CPPFLAGS += -DCONFIG_MSM_MMRM

# ported from Android.mk
$(info within KBUILD file KBUILD_EXTRA_SYMBOLS = $(KBUILD_EXTRA_SYMBOLS))

ifeq ($(CONFIG_ARCH_WAIPIO), y)
$(info within KBUILD file CONFIG_ARCH_WAIPIO = $(CONFIG_ARCH_WAIPIO))
# include $(EVA_ROOT)/config/waipio.mk
KBUILD_CPPFLAGS += -DCONFIG_EVA_WAIPIO=1
ccflags-y += -DCONFIG_EVA_WAIPIO=1
endif

ifeq ($(CONFIG_ARCH_KALAMA), y)
$(info within KBUILD file CONFIG_ARCH_KALAMA = $(CONFIG_ARCH_KALAMA))
# include $(EVA_ROOT)/config/waipio.mk
KBUILD_CPPFLAGS += -DCONFIG_EVA_KALAMA=1
ccflags-y += -DCONFIG_EVA_KALAMA=1
endif

ifeq ($(CONFIG_ARCH_PINEAPPLE), y)
$(info within KBUILD file CONFIG_ARCH_PINEAPPLE = $(CONFIG_ARCH_PINEAPPLE))
KBUILD_CPPFLAGS += -DCONFIG_EVA_PINEAPPLE=1 -DCVP_CONFIG_SYNX_V2=1
ccflags-y += -DCONFIG_EVA_PINEAPPLE=1 -DCVP_CONFIG_SYNX_V2=1
ccflags-y += -I$(EVA_ROOT)/../synx-kernel/msm/synx/ \
    -I$(EVA_ROOT)/../dsp-kernel/include/ \
    -I$(EVA_ROOT)/../synx-kernel/include/uapi/synx/media/
endif


ifeq ($(CONFIG_EVA_LE), 1)
ccflags-y += -DCONFIG_EVA_TVM=1
endif

msm-eva-objs := eva/cvp.o \
        eva/msm_cvp_ioctl.o \
        eva/msm_cvp_platform.o \
        eva/msm_cvp_common.o \
        eva/msm_cvp_core.o \
        eva/msm_cvp.o \
        eva/cvp_smem.o \
        eva/msm_cvp_debug.o \
        eva/msm_cvp_res_parse.o \
        eva/cvp_dump.o \
        eva/cvp_hfi.o \
        eva/hfi_response_handler.o \
        eva/hfi_packetization.o \
        eva/cvp_core_hfi.o \
        eva/msm_cvp_clocks.o\
        eva/msm_cvp_dsp.o \
        eva/msm_cvp_buf.o \
        eva/msm_cvp_synx.o \
	eva/cvp_fw_load.o \
	eva/cvp_power.o \
	eva/vm/cvp_vm_main.o \
	eva/vm/cvp_vm_msgq.o \
	eva/vm/cvp_vm_resource.o
obj-m += msm-eva.o

