# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.

export CONFIG_MSM_TOUCH=m
export CONFIG_TOUCH_FOCALTECH_FT3610=y
export CONFIG_QTS_ENABLE=y
export CONFIG_TOUCHSCREEN_ST=y
