def register_modules(registry):
    registry.register(
        name = "drivers/clk/qcom/av1ecc-x1p42100",
        out = "av1ecc-x1p42100.ko",
        config = "CONFIG_SC_AV1ECC_X1P42100",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/av1ecc-x1p42100.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/cambistmclkcc-canoe",
        out = "cambistmclkcc-canoe.ko",
        config = "CONFIG_SM_CAMBISTMCLKCC_CANOE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/cambistmclkcc-canoe.c",
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )
    registry.register(
        name = "drivers/clk/qcom/cambistmclkcc-sun",
        out = "cambistmclkcc-sun.ko",
        config = "CONFIG_SM_CAMBISTMCLKCC_SUN",
        srcs = [
            # do not sort
            "drivers/clk/qcom/cambistmclkcc-sun.c",
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/camcc-alor",
        out = "camcc-alor.ko",
        config = "CONFIG_SM_CAMCC_ALOR",
        srcs = [
            # do not sort
            "drivers/clk/qcom/camcc-alor.c",
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/gdsc.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/camcc-canoe",
        out = "camcc-canoe.ko",
        config = "CONFIG_SM_CAMCC_CANOE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/camcc-canoe.c",
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/gdsc.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )
    registry.register(
        name = "drivers/clk/qcom/camcc-chora",
        out = "camcc-chora.ko",
        config = "CONFIG_SM_CAMCC_CHORA",
        srcs = [
            # do not sort
            "drivers/clk/qcom/camcc-chora.c",
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/camcc-seraph",
        out = "camcc-seraph.ko",
        config = "CONFIG_SXR_CAMCC_SERAPH",
        srcs = [
            # do not sort
            "drivers/clk/qcom/camcc-seraph.c",
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/camcc-sun",
        out = "camcc-sun.ko",
        config = "CONFIG_SM_CAMCC_SUN",
        srcs = [
            # do not sort
            "drivers/clk/qcom/camcc-sun.c",
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/camcc-sc7280",
        out = "camcc-sc7280.ko",
        config = "CONFIG_SC_CAMCC_7280",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/camcc-sc7280.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/camcc-x1e80100",
        out = "camcc-x1e80100.ko",
        config = "CONFIG_CLK_X1E80100_CAMCC",
        srcs = [
            # do not sort
            "drivers/clk/qcom/camcc-x1e80100.c",
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/gdsc.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/camcc-x1p42100",
        out = "camcc-x1p42100.ko",
        config = "CONFIG_SC_CAMCC_X1P42100",
        srcs = [
            # do not sort
            "drivers/clk/qcom/camcc-x1p42100.c",
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/gdsc.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/clk-dummy",
        out = "clk-dummy.ko",
        config = "CONFIG_COMMON_CLK_QCOM",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-debug.h",
            "drivers/clk/qcom/clk-dummy.c",
            "drivers/clk/qcom/common.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/clk-qcom",
        out = "clk-qcom.ko",
        config = "CONFIG_COMMON_CLK_QCOM",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.c",
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.c",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-debug.c",
            "drivers/clk/qcom/clk-debug.h",
            "drivers/clk/qcom/clk-hfpll.c",
            "drivers/clk/qcom/clk-hfpll.h",
            "drivers/clk/qcom/clk-opp.c",
            "drivers/clk/qcom/clk-opp.h",
            "drivers/clk/qcom/clk-pll.c",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.c",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.c",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-rcg2.c",
            "drivers/clk/qcom/clk-regmap-divider.c",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux-div.c",
            "drivers/clk/qcom/clk-regmap-mux-div.h",
            "drivers/clk/qcom/clk-regmap-mux.c",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.c",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/clk-regmap.c",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.c",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc-debug.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/trace.h",
            "drivers/clk/qcom/vdd-class.c",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        conditional_srcs = {
            "CONFIG_KRAIT_CLOCKS": {
                True: [
                    # do not sort
                    "drivers/clk/qcom/clk-krait.c",
                    "drivers/clk/qcom/clk-krait.h",
                ],
            },
            "CONFIG_QCOM_GDSC": {
                True: [
                    # do not sort
                    "drivers/clk/qcom/gdsc.c",
                    "drivers/clk/qcom/gdsc-debug.c",
                ],
            },
        },
        deps = [
            # do not sort
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/interconnect/icc-clk",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/clk-smd-rpm",
        out = "clk-smd-rpm.ko",
        config = "CONFIG_QCOM_CLK_SMD_RPM",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-smd-rpm.c",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/clk-debug.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/rpmsg/rpm-smd",
            "drivers/soc/qcom/cmd-db",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/clk-rpmh",
        out = "clk-rpmh.ko",
        config = "CONFIG_QCOM_CLK_RPMH",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-rpmh.c",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/clk-debug.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/soc/qcom/qcom_rpmh",
            "drivers/soc/qcom/cmd-db",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/debugcc-alor",
        out = "debugcc-alor.ko",
        config = "CONFIG_SM_DEBUGCC_ALOR",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-debug.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/debugcc-alor.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-dummy",
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/debugcc-canoe",
        out = "debugcc-canoe.ko",
        config = "CONFIG_SM_DEBUGCC_CANOE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-debug.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/debugcc-canoe.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-dummy",
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/debugcc-khaje",
        out = "debugcc-khaje.ko",
        config = "CONFIG_SM_DEBUGCC_KHAJE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-debug.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/debugcc-khaje.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-dummy",
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/debugcc-monaco",
        out = "debugcc-monaco.ko",
        config = "CONFIG_SDW_DEBUGCC_MONACO",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-debug.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/debugcc-monaco.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-dummy",
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/debugcc-seraph",
        out = "debugcc-seraph.ko",
        config = "CONFIG_SXR_DEBUGCC_SERAPH",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-debug.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/debugcc-seraph.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-dummy",
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/debugcc-x1e80100",
        out = "debugcc-x1e80100.ko",
        config = "CONFIG_SC_DEBUGCC_X1E80100",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-debug.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/debugcc-x1e80100.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-dummy",
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gcc-sc7280",
        out = "gcc-sc7280.ko",
        config = "CONFIG_SC_GCC_7280",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gcc-sc7280.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/dispcc-monaco",
        out = "dispcc-monaco.ko",
        config = "CONFIG_SDW_DISPCC_MONACO",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/dispcc-monaco.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level-monaco.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/debugcc-sun",
        out = "debugcc-sun.ko",
        config = "CONFIG_SM_DEBUGCC_SUN",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-debug.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/debugcc-sun.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-dummy",
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/debugcc-vienna",
        out = "debugcc-vienna.ko",
        config = "CONFIG_SDW_DEBUGCC_VIENNA",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-debug.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/debugcc-vienna.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-dummy",
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/debugcc-sc7280",
        out = "debugcc-sc7280.ko",
        config = "CONFIG_SC_DEBUGCC_7280",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-debug.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/debugcc-sc7280.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-dummy",
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/dispcc-canoe",
        out = "dispcc-canoe.ko",
        config = "CONFIG_SM_DISPCC_CANOE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/dispcc-canoe.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/dispcc-khaje",
        out = "dispcc-khaje.ko",
        config = "CONFIG_SM_DISPCC_KHAJE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/dispcc-khaje.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level-bengal.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/dispcc-sc7280",
        out = "dispcc-sc7280.ko",
        config = "CONFIG_SC_DISPCC_7280",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/dispcc-sc7280.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/dispcc-sun",
        out = "dispcc-sun.ko",
        config = "CONFIG_SM_DISPCC_SUN",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/dispcc-sun.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/dispcc-x1e80100",
        out = "dispcc-x1e80100.ko",
        config = "CONFIG_CLK_X1E80100_DISPCC",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/dispcc-x1e80100.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/evacc-canoe",
        out = "evacc-canoe.ko",
        config = "CONFIG_SM_EVACC_CANOE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/evacc-canoe.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/evacc-seraph",
        out = "evacc-seraph.ko",
        config = "CONFIG_SXR_EVACC_SERAPH",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/evacc-seraph.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/evacc-sun",
        out = "evacc-sun.ko",
        config = "CONFIG_SM_EVACC_SUN",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/evacc-sun.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/lsrcc-seraph",
        out = "lsrcc-seraph.ko",
        config = "CONFIG_SXR_LSRCC_SERAPH",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/lsrcc-seraph.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gcc-alor",
        out = "gcc-alor.ko",
        config = "CONFIG_SM_GCC_ALOR",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gcc-alor.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/gdsc.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gcc-canoe",
        out = "gcc-canoe.ko",
        config = "CONFIG_SM_GCC_CANOE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gcc-canoe.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/gdsc.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gcc-chora",
        out = "gcc-chora.ko",
        config = "CONFIG_SM_GCC_CHORA",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gcc-chora.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/gdsc.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gcc-khaje",
        out = "gcc-khaje.ko",
        config = "CONFIG_SM_GCC_KHAJE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gcc-khaje.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level-bengal.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gcc-monaco",
        out = "gcc-monaco.ko",
        config = "CONFIG_SDW_GCC_MONACO",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gcc-monaco.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level-monaco.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gcc-seraph",
        out = "gcc-seraph.ko",
        config = "CONFIG_SXR_GCC_SERAPH",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gcc-seraph.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gcc-sun",
        out = "gcc-sun.ko",
        config = "CONFIG_SM_GCC_SUN",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gcc-sun.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gcc-vienna",
        out = "gcc-vienna.ko",
        config = "CONFIG_SDW_GCC_VIENNA",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gcc-vienna.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gcc-x1p42100",
        out = "gcc-x1p42100.ko",
        config = "CONFIG_SC_GCC_X1P42100",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gcc-x1p42100.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gcc-x1e80100",
        out = "gcc-x1e80100.ko",
        config = "CONFIG_CLK_X1E80100_GCC",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gcc-x1e80100.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gdsc-regulator",
        out = "gdsc-regulator.ko",
        config = "CONFIG_QCOM_GDSC_REGULATOR",
        srcs = [
            # do not sort
            "drivers/clk/qcom/gdsc-debug.h",
            "drivers/clk/qcom/gdsc-regulator.c",
            "drivers/clk/qcom/trace-gdsc.h",
        ],
        deps = [
            # do not sort
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gpucc-canoe",
        out = "gpucc-canoe.ko",
        config = "CONFIG_SM_GPUCC_CANOE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/gpucc-canoe.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gpucc-khaje",
        out = "gpucc-khaje.ko",
        config = "CONFIG_SM_GPUCC_KHAJE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gpucc-khaje.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level-bengal.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gpucc-monaco",
        out = "gpucc-monaco.ko",
        config = "CONFIG_SDW_GPUCC_MONACO",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gpucc-monaco.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level-monaco.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gpucc-seraph",
        out = "gpucc-seraph.ko",
        config = "CONFIG_SXR_GPUCC_SERAPH",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/gpucc-seraph.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gpucc-sun",
        out = "gpucc-sun.ko",
        config = "CONFIG_SM_GPUCC_SUN",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/gpucc-sun.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gpucc-vienna",
        out = "gpucc-vienna.ko",
        config = "CONFIG_SDW_GPUCC_VIENNA",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/gpucc-vienna.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gpucc-sc7280",
        out = "gpucc-sc7280.ko",
        config = "CONFIG_SC_GPUCC_7280",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gpucc-sc7280.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gpucc-x1e80100",
        out = "gpucc-x1e80100.ko",
        config = "CONFIG_CLK_X1E80100_GPUCC",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/gpucc-x1e80100.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/gpucc-x1p42100",
        out = "gpucc-x1p42100.ko",
        config = "CONFIG_CLK_X1P42100_GPUCC",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/gpucc-x1p42100.c",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/lpassaoncc-khaje",
        out = "lpassaoncc-khaje.ko",
        config = "CONFIG_SM_LPASS_AUDIOCC_KHAJE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/lpassaoncc-khaje.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level-bengal.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/lpassaudiocc-khaje",
        out = "lpassaudiocc-khaje.ko",
        config = "CONFIG_SM_LPASS_AUDIOCC_KHAJE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/lpassaudiocc-khaje.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level-bengal.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/tcsrcc-canoe",
        out = "tcsrcc-canoe.ko",
        config = "CONFIG_SM_TCSRCC_CANOE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/tcsrcc-canoe.c",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/tcsrcc-chora",
        out = "tcsrcc-chora.ko",
        config = "CONFIG_SM_TCSRCC_CHORA",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/tcsrcc-chora.c",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/tcsrcc-seraph",
        out = "tcsrcc-seraph.ko",
        config = "CONFIG_SXR_TCSRCC_SERAPH",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/tcsrcc-seraph.c",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/tcsrcc-sun",
        out = "tcsrcc-sun.ko",
        config = "CONFIG_SM_TCSRCC_SUN",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/tcsrcc-sun.c",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/tcsrcc-x1e80100",
        out = "tcsrcc-x1e80100.ko",
        config = "CONFIG_CLK_X1E80100_TCSRCC",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/tcsrcc-x1e80100.c",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/videocc-canoe",
        out = "videocc-canoe.ko",
        config = "CONFIG_SM_VIDEOCC_CANOE",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/videocc-canoe.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/videocc-chora",
        out = "videocc-chora.ko",
        config = "CONFIG_SM_VIDEOCC_CHORA",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/videocc-chora.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/videocc-seraph",
        out = "videocc-seraph.ko",
        config = "CONFIG_SXR_VIDEOCC_SERAPH",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-pm.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/videocc-seraph.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/videocc-sm8550",
        out = "videocc-sm8550.ko",
        config = "CONFIG_SM_VIDEOCC_8550",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/videocc-sm8550.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/videocc-sun",
        out = "videocc-sun.ko",
        config = "CONFIG_SM_VIDEOCC_SUN",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/videocc-sun.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/virtio_clk",
        out = "virtio_clk.ko",
        config = "CONFIG_VIRTIO_CLK",
        srcs = [
            # do not sort
            "drivers/clk/qcom/virtio_clk.c",
            "drivers/clk/qcom/virtio_clk_common.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/virtio_clk_direwolf",
            "drivers/clk/qcom/virtio_clk_lemans",
            "drivers/clk/qcom/virtio_clk_monaco",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/virtio_clk_direwolf",
        out = "virtio_clk_direwolf.ko",
        config = "CONFIG_VIRTIO_CLK",
        srcs = [
            # do not sort
            "drivers/clk/qcom/virtio_clk_direwolf.c",
            "drivers/clk/qcom/virtio_clk_common.h",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/virtio_clk_lemans",
        out = "virtio_clk_lemans.ko",
        config = "CONFIG_VIRTIO_CLK",
        srcs = [
            # do not sort
            "drivers/clk/qcom/virtio_clk_lemans.c",
            "drivers/clk/qcom/virtio_clk_common.h",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/virtio_clk_monaco",
        out = "virtio_clk_monaco.ko",
        config = "CONFIG_VIRTIO_CLK",
        srcs = [
            # do not sort
            "drivers/clk/qcom/virtio_clk_monaco.c",
            "drivers/clk/qcom/virtio_clk_common.h",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/videocc-sc7280",
        out = "videocc-sc7280.ko",
        config = "CONFIG_SC_VIDEOCC_7280",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/videocc-sc7280.c",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/clk-regmap-phy-mux.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
        ],
    )

    registry.register(
        name = "drivers/clk/qcom/videocc-x1p42100",
        out = "videocc-x1p42100.ko",
        config = "CONFIG_SC_VIDEOCC_X1P42100",
        srcs = [
            # do not sort
            "drivers/clk/qcom/clk-alpha-pll.h",
            "drivers/clk/qcom/clk-branch.h",
            "drivers/clk/qcom/clk-pll.h",
            "drivers/clk/qcom/clk-rcg.h",
            "drivers/clk/qcom/clk-regmap-divider.h",
            "drivers/clk/qcom/clk-regmap-mux.h",
            "drivers/clk/qcom/clk-regmap.h",
            "drivers/clk/qcom/common.h",
            "drivers/clk/qcom/gdsc.h",
            "drivers/clk/qcom/reset.h",
            "drivers/clk/qcom/vdd-class.h",
            "drivers/clk/qcom/vdd-level.h",
            "drivers/clk/qcom/videocc-x1p42100.c",
        ],
        deps = [
            # do not sort
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )
