ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_i2c_trigger.o
#MM-MC-BringUpCameraFlashLM3642-00-{
#obj-$(CONFIG_MSMB_CAMERA) += adp1660.o
#MM-MC-BringUpCameraFlashLM3642-00-}
obj-$(CONFIG_MSMB_CAMERA) += msm_led_torch.o
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
#MM-MC-BringUpCameraFlashLM3642-00+{
obj-$(CONFIG_MSMB_CAMERA) += lm3642_fih.o
#MM-MC-BringUpCameraFlashLM3642-00+{
