LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := cirrus_cs40l2x_codec.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)

CIRRUS_CS40L2X_PATH := vendor/cirrus/kernel-modules/cs40l25/drivers/misc
KBUILD_OPTIONS := CIRRUS_CS40L2X_PATH=$(CIRRUS_CS40L2X_PATH)
KBUILD_OPTIONS_GKI := CIRRUS_CS40L2X_PATH=$(CIRRUS_CS40L2X_PATH)/gki

LOCAL_ADDITIONAL_DEPENDENCIES := $(TARGET_OUT_INTERMEDIATES)/$(CIRRUS_CS40L2X_PATH)/cirrus_cs40l2x.ko
LOCAL_ADDITIONAL_DEPENDENCIES_GKI := $(TARGET_OUT_INTERMEDIATES)/$(CIRRUS_CS40L2X_PATH)/gki/cirrus_cs40l2x.ko
include $(TOP)/device/qcom/common/dlkm/AndroidKernelModule.mk
