obj-$(CONFIG_FELICA_SNFC)		+= felica_snfc.o
obj-$(CONFIG_FELICA_VDEV)		+= felica_vdev.o
obj-$(CONFIG_CXD2235AGG)		+= cxd2235agg.o
obj-$(CONFIG_CXD224X_NFC)		+= cxd224x-i2c.o
obj-$(CONFIG_BD7602_POWER_IC)		+= bd7602.o
