/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2021, The Linux Foundation. All rights reserved.
 * Copyright (c) 2022-2024 Qualcomm Innovation Center, Inc. All rights reserved.
 */

/* RMNET WLAN stats framework */

#ifndef __RMNET_WLAN_STATS_H__
#define __RMNET_WLAN_STATS_H__

#include <linux/types.h>

enum {
	RMNET_WLAN_STAT_TUPLE_ADD,
	RMNET_WLAN_STAT_TUPLE_DEL,
	RMNET_WLAN_STAT_PKT_RX,
	RMNET_WLAN_STAT_PKT_FWD,
	RMNET_WLAN_STAT_PKT_FWD_NO_DEV,
	RMNET_WLAN_STAT_FRAG_RX,
	RMNET_WLAN_STAT_FRAG_FWD,
	RMNET_WLAN_STAT_FRAG_FWD_NO_DEV,
	RMNET_WLAN_STAT_FRAG_QUEUE,
	RMNET_WLAN_STAT_FRAG_EXP,
	RMNET_WLAN_STAT_ENCAP_DELIVER,
	RMNET_WLAN_STAT_MSS_CLAMP,
	RMNET_WLAN_STAT_MSS_CLAMP_SKIP,
	RMNET_WLAN_STAT_MSS_CLAMP_ERR,
	RMNET_WLAN_STAT_ENCAP_PORT_ADD,
	RMNET_WLAN_STAT_ENCAP_PORT_DEL,
	RMNET_WLAN_STAT_ENCAP_PORT_DROP_ADD,
	RMNET_WLAN_STAT_ENCAP_PORT_DROP_DEL,
	RMNET_WLAN_STAT_ENCAP_DROP,
	RMNET_WWAN_STAT_PKT_RX,
	RMNET_WLAN_STAT_ENCAP_HDRP_FAIL,
	RMNET_WLAN_STAT_LL_TX,
	RMNET_WLAN_STAT_CIWLAN_DDEV_GET_FAIL,
	RMNET_WLAN_STAT_MAX,
};

/* fowarding stats */
enum {
	RMNET_WLAN_F_S_R0_IP_XMIT_SUCCESS,
	RMNET_WLAN_F_S_R0_IPV6_XMIT_SUCCESS,
	RMNET_WLAN_F_S_R0_IP_XMIT_DROP,
	RMNET_WLAN_F_S_R0_IPV6_XMIT_DROP,
	RMNET_WLAN_F_S_R0_IP_HDRP_FAIL,
	RMNET_WLAN_F_S_R0_IP_DEV_GET_FAIL,
	RMNET_WLAN_F_S_R0_IP_ROUTE_FAIL,
	RMNET_WLAN_F_S_R0_IP_NEIGH_LOOKUP_FAIL,
	RMNET_WLAN_F_S_R0_IP_HARD_HEADER_FAIL,
	RMNET_WLAN_F_S_R0_IPV6_HDRP_FAIL,
	RMNET_WLAN_F_S_R0_IPV6_DEV_GET_FAIL,
	RMNET_WLAN_F_S_R0_IPV6_ROUTE_FAIL,
	RMNET_WLAN_F_S_R0_IPV6_NEIGH_LOOKUP_FAIL,
	RMNET_WLAN_F_S_R0_IPV6_HARD_HEADER_FAIL,
	RMNET_WLAN_F_S_NON_R0_IPV6_HDRP_FAIL,
	RMNET_WLAN_F_S_NON_R0_IPV6_DST_LOOKUP_FAIL,
	RMNET_WLAN_F_S_NON_R0_IPV6_XFRM_LOOKUP_FAIL,
	RMNET_WLAN_F_S_NON_R0_IPV6_DST_OUTPUT_SUCCESS,
	RMNET_WLAN_F_S_NON_R0_IP_HDRP_FAIL,
	RMNET_WLAN_F_S_NON_R0_IP_RT_LOOKUP_FAIL,
	RMNET_WLAN_F_S_NON_R0_IP_XFRM_LOOKUP_FAIL,
	RMNET_WLAN_F_S_NON_R0_IP_DST_OUTPUT_SUCCESS,
	RMNET_WLAN_F_S_R0_IPV6_DDEV_GET_FAIL,
	RMNET_WLAN_F_S_NON_R0_IPV6_DDST_LOOKUP_FAIL,
	RMNET_WLAN_F_S_R0_IP_DDEV_GET_FAIL,
	RMNET_WLAN_F_S_NON_R0_IP_DRT_LOOKUP_FAIL,
	RMNET_WWAN_F_S_NON_R0_IPV6_HDRP_FAIL,
	RMNET_WWAN_F_S_NON_R0_IPV6_DST_LOOKUP_FAIL,
	RMNET_WWAN_F_S_NON_R0_IPV6_XFRM_LOOKUP_FAIL,
	RMNET_WWAN_F_S_NON_R0_IPV6_DST_OUTPUT_SUCCESS,
	RMNET_WWAN_F_S_R0_IPV6_DDEV_GET_FAIL,
	RMNET_WWAN_F_S_NON_R0_IPV6_DDST_LOOKUP_FAIL,
	RMNET_WWAN_F_S_NON_R0_IP_HDRP_FAIL,
	RMNET_WWAN_F_S_NON_R0_IP_RT_LOOKUP_FAIL,
	RMNET_WWAN_F_S_NON_R0_IP_XFRM_LOOKUP_FAIL,
	RMNET_WWAN_F_S_NON_R0_IP_DST_OUTPUT_SUCCESS,
	RMNET_WWAN_F_S_R0_IP_DDEV_GET_FAIL,
	RMNET_WWAN_F_S_NON_R0_IP_DRT_LOOKUP_FAIL,
	RMNET_WWAN_F_S_R0_IP_DEV_GET_FAIL,
	RMNET_WWAN_F_S_R0_IPV6_DEV_GET_FAIL,
	RMNET_WWAN_F_S_R0_IP_ROUTE_FAIL,
	RMNET_WWAN_F_S_R0_IP_HDRP_FAIL,
	RMNET_WLAN_F_S_NON_R0_IP_DEV_GET_FAIL,
	RMNET_F_S_PULL_PROTO_MISMATCH,
	RMNET_F_S_PULL_SUCCESS,
	RMNET_F_S_PULL_FAILURE,
	RMNET_WLAN_F_S_R0_MAX,
};

void rmnet_wlan_stats_update(u32 stat);
void rmnet_wlan_forward_stats_update(u32 stat);

#endif
