/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2021, The Linux Foundation. All rights reserved.
 * Copyright (c) 2022, 2024, Qualcomm Innovation Center, Inc. All rights reserved.
 */

/* RMNET WLAN Generic netlink */

#ifndef __RMNET_WLAN_GENL_H__
#define __RMNET_WLAN_GENL_H__

#define RMNET_WLAN_GENL_VERSION 1
#define RMNET_WLAN_GENL_FAMILY_NAME "RMNET_WLAN"

enum {
	RMNET_WLAN_GENL_CMD_UNSPEC,
	RMNET_WLAN_GENL_CMD_ADD_TUPLES,
	RMNET_WLAN_GENL_CMD_DEL_TUPLES,
	RMNET_WLAN_GENL_CMD_SET_DEV,
	RMNET_WLAN_GENL_CMD_UNSET_DEV,
	RMNET_WLAN_GENL_CMD_ADD_FWD_INFO,
	RMNET_WLAN_GENL_CMD_DEL_FWD_INFO,
	RMNET_WLAN_GENL_CMD_SET_ENCAP_PORT,
	RMNET_WLAN_GENL_CMD_UNSET_ENCAP_PORT,
	RMNET_WLAN_GENL_CMD_RESET,
	RMNET_WLAN_GENL_CMD_ENCAP_PORT_ACT_PASS_THROUGH,
	RMNET_WLAN_GENL_CMD_ENCAP_PORT_ACT_DROP,
	RMNET_WLAN_GENL_CMD_LL_ADDR_ADD,
	RMNET_WLAN_GENL_CMD_LL_ADDR_DEL,
	RMNET_WLAN_GENL_CMD_GET_TUPLES,
	__RMNET_WLAN_GENL_CMD_MAX,
};

enum {
	RMNET_WLAN_GENL_ATTR_UNSPEC,
	RMNET_WLAN_GENL_ATTR_TUPLES,
	RMNET_WLAN_GENL_ATTR_DEV,
	RMNET_WLAN_GENL_ATTR_FWD_ADDR,
	RMNET_WLAN_GENL_ATTR_FWD_DEV,
	RMNET_WLAN_GENL_ATTR_ENCAP_PORT,
	RMNET_WLAN_GENL_ATTR_NET_TYPE,
	RMNET_WLAN_GENL_ATTR_LL_SRC_ADDR,
	RMNET_WLAN_GENL_ATTR_LL_DST_ADDR,
	RMNET_WLAN_GENL_ATTR_LL_SRC_PORT,
	RMNET_WLAN_GENL_ATTR_LL_DST_PORT,
	__RMNET_WLAN_GENL_ATTR_MAX,
};

#define RMNET_WLAN_GENL_ATTR_MAX (__RMNET_WLAN_GENL_ATTR_MAX - 1)

enum {
	RMNET_WLAN_GENL_TUPLE_ATTR_UNSPEC,
	RMNET_WLAN_GENL_TUPLE_ATTR_TUPLE,
	__RMNET_WLAN_GENL_TUPLE_ATTR_MAX,
};

#define RMNET_WLAN_GENL_TUPLE_ATTR_MAX (__RMNET_WLAN_GENL_TUPLE_ATTR_MAX - 1)

#define DATA_PATH_PROXY_NET_MAX (__DATA_PATH_PROXY_NET_MAX - 1)

#endif
