load(":drivers/usb/dwc3/modules.bzl", register_dwc3 = "register_modules")
load(":drivers/usb/gadget/function/modules.bzl", register_gadget_function = "register_modules")
load(":drivers/usb/misc/modules.bzl", register_misc = "register_modules")
load(":drivers/usb/phy/modules.bzl", register_phy = "register_modules")
load(":drivers/usb/redriver/modules.bzl", register_redriver = "register_modules")
load(":drivers/usb/repeater/modules.bzl", register_repeater = "register_modules")
load(":drivers/usb/typec/ucsi/modules.bzl", register_typec_ucsi = "register_modules")

def register_modules(registry):
    register_dwc3(registry)
    register_gadget_function(registry)
    register_misc(registry)
    register_phy(registry)
    register_redriver(registry)
    register_repeater(registry)
    register_typec_ucsi(registry)
