load(":drivers/base/regmap/modules.bzl", register_base_regmap = "register_modules")
load(":drivers/block/modules.bzl", register_block = "register_modules")
load(":drivers/bus/modules.bzl", register_bus = "register_modules")
load(":drivers/char/modules.bzl", register_char = "register_modules")
load(":drivers/clk/modules.bzl", register_clk = "register_modules")
load(":drivers/cpufreq/modules.bzl", register_cpufreq = "register_modules")
load(":drivers/cpuidle/governors/modules.bzl", register_cpuidle_governors = "register_modules")
load(":drivers/crypto/modules.bzl", register_crypto = "register_modules")
load(":drivers/devfreq/modules.bzl", register_devfreq = "register_modules")
load(":drivers/dma/modules.bzl", register_dma = "register_modules")
load(":drivers/dma-buf/heaps/modules.bzl", register_dma_buf_heaps = "register_modules")
load(":drivers/edac/modules.bzl", register_edac = "register_modules")
load(":drivers/eom/modules.bzl", register_eom_driver = "register_modules")
load(":drivers/eom/pcie/modules.bzl", register_pci_phy_access = "register_modules")
load(":drivers/firmware/modules.bzl", register_firmware = "register_modules")
load(":drivers/gpio/modules.bzl", register_gpio = "register_modules")
load(":drivers/gpu/drm/bridge/modules.bzl", register_gpu_drm_bridge = "register_modules")
load(":drivers/gpu/drm/display/modules.bzl", register_gpu_drm_display = "register_modules")
load(":drivers/hwmon/modules.bzl", register_hwmon = "register_modules")
load(":drivers/hwspinlock/modules.bzl", register_hwspinlock = "register_modules")
load(":drivers/hwtracing/modules.bzl", register_hwtracing = "register_modules")
load(":drivers/i2c/busses/modules.bzl", register_i2c_busses = "register_modules")
load(":drivers/i3c/master/modules.bzl", register_i3c_master = "register_modules")
load(":drivers/iio/adc/modules.bzl", register_iio_adc = "register_modules")
load(":drivers/input/misc/modules.bzl", register_input_misc = "register_modules")
load(":drivers/input/touchscreen/lxs_ts/modules.bzl", register_input_touchscreen_lxs_ts = "register_modules")
load(":drivers/interconnect/modules.bzl", register_interconnect = "register_modules")
load(":drivers/interconnect/qcom/modules.bzl", register_interconnect_qcom = "register_modules")
load(":drivers/iommu/modules.bzl", register_iommu = "register_modules")
load(":drivers/irqchip/modules.bzl", register_irqchip = "register_modules")
load(":drivers/leds/modules.bzl", register_leds = "register_modules")
load(":drivers/mailbox/modules.bzl", register_mailbox = "register_modules")
load(":drivers/mfd/modules.bzl", register_mfd = "register_modules")
load(":drivers/misc/modules.bzl", register_misc = "register_modules")
load(":drivers/mmc/core/modules.bzl", register_mmc_core = "register_modules")
load(":drivers/mmc/host/modules.bzl", register_mmc_host = "register_modules")
load(":drivers/net/modules.bzl", register_net = "register_modules")
load(":drivers/nvmem/modules.bzl", register_nvmem = "register_modules")
load(":drivers/pci/controller/modules.bzl", register_pci_controller = "register_modules")
load(":drivers/perf/modules.bzl", register_perf = "register_modules")
load(":drivers/phy/qualcomm/modules.bzl", register_phy_qualcomm = "register_modules")
load(":drivers/pinctrl/qcom/modules.bzl", register_pinctrl_qcom = "register_modules")
load(":drivers/power/modules.bzl", register_power = "register_modules")
load(":drivers/powercap/qcom/modules.bzl", register_powercap_qcom = "register_modules")
load(":drivers/regulator/modules.bzl", register_regulator = "register_modules")
load(":drivers/remoteproc/modules.bzl", register_remoteproc = "register_modules")
load(":drivers/rpmsg/modules.bzl", register_rpmsg = "register_modules")
load(":drivers/rtc/modules.bzl", register_rtc = "register_modules")
load(":drivers/scsi/modules.bzl", register_scsi = "register_modules")
load(":drivers/slimbus/modules.bzl", register_slimbus = "register_modules")
load(":drivers/soc/modules.bzl", register_soc = "register_modules")
load(":drivers/spi/modules.bzl", register_spi = "register_modules")
load(":drivers/spmi/modules.bzl", register_spmi = "register_modules")
load(":drivers/thermal/qcom/modules.bzl", register_thermal_qcom = "register_modules")
load(":drivers/tty/modules.bzl", register_tty = "register_modules")
load(":drivers/ufs/host/modules.bzl", register_ufs_host = "register_modules")
load(":drivers/uio/msm_sharedmem/modules.bzl", register_uio_msm_sharedmem = "register_modules")
load(":drivers/usb/modules.bzl", register_usb = "register_modules")
load(":drivers/video/modules.bzl", register_video = "register_modules")
load(":drivers/virt/modules.bzl", register_virt = "register_modules")
load(":drivers/input/et617/modules.bzl", register_input_et617 = "register_modules")
load(":drivers/virtio/modules.bzl", register_virtio = "register_modules")

def register_modules(registry):
    register_base_regmap(registry)
    register_block(registry)
    register_bus(registry)
    register_char(registry)
    register_clk(registry)
    register_cpufreq(registry)
    register_cpuidle_governors(registry)
    register_crypto(registry)
    register_devfreq(registry)
    register_dma(registry)
    register_dma_buf_heaps(registry)
    register_edac(registry)
    register_firmware(registry)
    register_gpio(registry)
    register_gpu_drm_bridge(registry)
    register_gpu_drm_display(registry)
    register_hwmon(registry)
    register_hwspinlock(registry)
    register_hwtracing(registry)
    register_i2c_busses(registry)
    register_i3c_master(registry)
    register_iio_adc(registry)
    register_input_misc(registry)
    register_input_touchscreen_lxs_ts(registry)
    register_interconnect(registry)
    register_interconnect_qcom(registry)
    register_iommu(registry)
    register_irqchip(registry)
    register_leds(registry)
    register_mailbox(registry)
    register_mfd(registry)
    register_misc(registry)
    register_mmc_core(registry)
    register_mmc_host(registry)
    register_net(registry)
    register_nvmem(registry)
    register_pci_controller(registry)
    register_eom_driver(registry)
    register_pci_phy_access(registry)
    register_perf(registry)
    register_phy_qualcomm(registry)
    register_pinctrl_qcom(registry)
    register_power(registry)
    register_powercap_qcom(registry)
    register_regulator(registry)
    register_remoteproc(registry)
    register_rpmsg(registry)
    register_rtc(registry)
    register_scsi(registry)
    register_slimbus(registry)
    register_soc(registry)
    register_spi(registry)
    register_spmi(registry)
    register_thermal_qcom(registry)
    register_tty(registry)
    register_ufs_host(registry)
    register_uio_msm_sharedmem(registry)
    register_usb(registry)
    register_video(registry)
    register_virt(registry)
    register_input_et617(registry)
    register_virtio(registry)
