dtb-$(CONFIG_MACH_SONY_PIONEER)	+= sdm630-ganges-pioneer.dtb
dtb-$(CONFIG_MACH_SONY_KIRIN) += sdm630-ganges-kirin.dtb
dtb-$(CONFIG_MACH_SONY_KIRIN_DSDS) += sdm630-ganges-kirin_dsds.dtb
dtb-$(CONFIG_MACH_SONY_MERMAID) += sdm636-ganges-mermaid.dtb \
	sdm630-ganges-mermaid.dtb
dtb-$(CONFIG_MACH_SONY_MERMAID_DSDS) += sdm636-ganges-mermaid_dsds.dtb \
	sdm630-ganges-mermaid_dsds.dtb


always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
