/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef __DT_BINDINGS_INTERCONNECT_QCOM_X1P42100_H
#define __DT_BINDINGS_INTERCONNECT_QCOM_X1P42100_H

#define MASTER_GPU_TCU				0
#define MASTER_PCIE_TCU				1
#define MASTER_SYS_TCU				2
#define MASTER_APPSS_PROC				3
#define MASTER_LLCC				4
#define MASTER_QSPI_0				5
#define MASTER_QUP_0				6
#define MASTER_QUP_1				7
#define MASTER_QUP_2				8
#define MASTER_A1NOC_SNOC				9
#define MASTER_A2NOC_SNOC				10
#define MASTER_AGGRE_USB_NORTH				11
#define MASTER_AGGRE_USB_SOUTH				12
#define MASTER_AV1_ENC				13
#define MASTER_CAMNOC_HF				14
#define MASTER_CAMNOC_ICP				15
#define MASTER_CAMNOC_SF				16
#define MASTER_EVA				17
#define MASTER_GEM_NOC_CNOC				18
#define MASTER_GEM_NOC_PCIE_SNOC				19
#define MASTER_NSINOC				20
#define MASTER_GFX3D				21
#define MASTER_LPASS_GEM_NOC				22
#define MASTER_LPASS_LPINOC				23
#define MASTER_LPIAON_NOC				24
#define MASTER_MDP				25
#define MASTER_MNOC_HF_MEM_NOC				26
#define MASTER_MNOC_SF_MEM_NOC				27
#define MASTER_COMPUTE_NOC				28
#define MASTER_ANOC_PCIE_GEM_NOC				29
#define MASTER_PCIE_NORTH				30
#define MASTER_PCIE_SOUTH				31
#define MASTER_SNOC_SF_MEM_NOC				32
#define MASTER_USB_NOC_SNOC				33
#define MASTER_VIDEO				34
#define MASTER_VIDEO_CV_PROC				35
#define MASTER_VIDEO_V_PROC				36
#define MASTER_CNOC_CFG				37
#define MASTER_CNOC_MNOC_CFG				38
#define MASTER_QUP_CORE_0				39
#define MASTER_QUP_CORE_1				40
#define MASTER_QUP_CORE_2				41
#define MASTER_CRYPTO				42
#define MASTER_LPASS_PROC				43
#define MASTER_CDSP_PROC				44
#define MASTER_SP				45
#define MASTER_WLAN_Q6				46
#define MASTER_GIC				47
#define MASTER_PCIE_0				48
#define MASTER_PCIE_1				49
#define MASTER_PCIE_2				50
#define MASTER_PCIE_3				51
#define MASTER_PCIE_4				52
#define MASTER_PCIE_5				53
#define MASTER_PCIE_6A				54
#define MASTER_QDSS_ETR				55
#define MASTER_QDSS_ETR_1				56
#define MASTER_SDCC_2				57
#define MASTER_SDCC_4				58
#define MASTER_UFS_MEM				59
#define MASTER_USB2				60
#define MASTER_USB3_0				61
#define MASTER_USB3_1				62
#define MASTER_USB3_2				63
#define MASTER_USB3_MP				64
#define MASTER_USB4_0				65
#define MASTER_USB4_1				66
#define MASTER_USB4_2				67
#define SLAVE_EBI1				512
#define SLAVE_AHB2PHY_SOUTH				513
#define SLAVE_AHB2PHY_NORTH				514
#define SLAVE_AOSS				515
#define SLAVE_AV1_ENC_CFG				516
#define SLAVE_CAMERA_CFG				517
#define SLAVE_CLK_CTL				518
#define SLAVE_CRYPTO_0_CFG				519
#define SLAVE_DISPLAY_CFG				520
#define SLAVE_GFX3D_CFG				521
#define SLAVE_IMEM_CFG				522
#define SLAVE_IPC_ROUTER_CFG				523
#define SLAVE_PCIE_0_CFG				524
#define SLAVE_PCIE_1_CFG				525
#define SLAVE_PCIE_2_CFG				526
#define SLAVE_PCIE_3_CFG				527
#define SLAVE_PCIE_4_CFG				528
#define SLAVE_PCIE_5_CFG				529
#define SLAVE_PCIE_6A_CFG				530
#define SLAVE_PCIE_RSC_CFG				531
#define SLAVE_PDM				532
#define SLAVE_PRNG				533
#define SLAVE_QDSS_CFG				534
#define SLAVE_QSPI_0				535
#define SLAVE_QUP_0				536
#define SLAVE_QUP_1				537
#define SLAVE_QUP_2				538
#define SLAVE_SDCC_2				539
#define SLAVE_SDCC_4				540
#define SLAVE_SMMUV3_CFG				541
#define SLAVE_TCSR				542
#define SLAVE_TLMM				543
#define SLAVE_TME_CFG				544
#define SLAVE_UFS_MEM_CFG				545
#define SLAVE_USB2				546
#define SLAVE_USB3_0				547
#define SLAVE_USB3_1				548
#define SLAVE_USB3_2				549
#define SLAVE_USB3_MP				550
#define SLAVE_USB4_0				551
#define SLAVE_USB4_1				552
#define SLAVE_USB4_2				553
#define SLAVE_VENUS_CFG				554
#define SLAVE_A1NOC_SNOC				555
#define SLAVE_A2NOC_SNOC				556
#define SLAVE_AGGRE_USB_NORTH				557
#define SLAVE_USB_NOC_SNOC				558
#define SLAVE_AGGRE_USB_SOUTH				559
#define SLAVE_APPSS				560
#define SLAVE_GEM_NOC_CNOC				561
#define SLAVE_SNOC_GEM_NOC_SF				562
#define SLAVE_LLCC				563
#define SLAVE_LPASS_GEM_NOC				564
#define SLAVE_LPIAON_NOC_LPASS_AG_NOC				565
#define SLAVE_LPICX_NOC_LPIAON_NOC				566
#define SLAVE_MNOC_HF_MEM_NOC				567
#define SLAVE_MNOC_SF_MEM_NOC				568
#define SLAVE_CDSP_MEM_NOC				569
#define SLAVE_MEM_NOC_PCIE_SNOC				570
#define SLAVE_ANOC_PCIE_GEM_NOC				571
#define SLAVE_PCIE_NORTH				572
#define SLAVE_PCIE_SOUTH				573
#define SLAVE_CNOC_CFG				574
#define SLAVE_LPASS_QTB_CFG				575
#define SLAVE_CNOC_MNOC_CFG				576
#define SLAVE_NSP_QTB_CFG				577
#define SLAVE_QUP_CORE_0				578
#define SLAVE_QUP_CORE_1				579
#define SLAVE_QUP_CORE_2				580
#define SLAVE_BOOT_IMEM				581
#define SLAVE_IMEM				582
#define SLAVE_SERVICE_MNOC				583
#define SLAVE_PCIE_0				584
#define SLAVE_PCIE_1				585
#define SLAVE_PCIE_2				586
#define SLAVE_PCIE_3				587
#define SLAVE_PCIE_4				588
#define SLAVE_PCIE_5				589
#define SLAVE_PCIE_6A				590
#define SLAVE_QDSS_STM				591
#define SLAVE_TCU				592

#endif
