#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

# obj-$(CONFIG_CEI_HARDWARE_ID)     += cei_gpio_init.o
obj-$(CONFIG_CEI_HARDWARE_ID)     += cei_hw_id.o
