/* SPDX-License-Identifier: GPL-2.0-only
 * Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
 */
#define CONFIG_MSM_QDSP6_SSR 1
#define CONFIG_MSM_ADSP_LOADER 1
#define CONFIG_MSM_QDSP6_NOTIFIER 1
#define CONFIG_SND_SOC_MSM_QDSP6V2_INTF 1
#define CONFIG_SND_SOC_QDSP6V2 1
#define CONFIG_MSM_QDSP6_GPR_RPMSG 1
#define CONFIG_AUDIO_PKT 1
#define CONFIG_AUDIO_PKT_ION 1
#define CONFIG_AUDIO_PRM 1
#define CONFIG_SPF_CORE 1
#define CONFIG_SND_EVENT 1
#define CONFIG_SND_SOC_MSM_STUB 1
#define CONFIG_SND_SOC_SA7255_AUTO_SPF 1
#define CONFIG_PINCTRL_LPI 1
#define CONFIG_SND_SOC_WCD9XXX_V2 1
#define CONFIG_DIGITAL_CDC_RSC_MGR 1
